# Nom de l'application
spring.application.name=cmda-system-management

# Configuration de la base de donnees
spring.datasource.url=jdbc:mysql://localhost:3306/cmda_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurations JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuration du serveur
server.error.whitelabel.enabled=true

# Configuration de la vue
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
spring.thymeleaf.enabled=true

# Configuration de Swagger
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html

# Configuration du logging
logging.file.name=logs/cmda-management.log
logging.level.org.springframework=INFO
logging.level.org.cmda.management=DEBUG
logging.file.path=./logs
logging.file.max-size=10MB
logging.file.max-history=30

# Configuration de la gestion de references circulaires
spring.main.allow-circular-references=true

# Cle secrete pour le JWT
#jwt.secret-key=cmda-secret-key
#jwt.secret-key=VXBkYXRlVGhpcyB3aXRoIHlvdXIgYmFzZTY0IGtleQ==
jwt.secret-key=c29tZXNlY3JldGtleWJhc2U2NGZvcmFwcGxpY2F0aW9u

